//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Class
    {
        public Class()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int Id { get; set; }

        [DisplayName("名稱")]
        [Required]              //必填項目
        [StringLength(10)]      //字串最大長度
        [RegularExpression("")] //標準表達試
        [Range(0, 100)]          //數字允許的範圍
        public string Name { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
    }
}
